---

language: ruby
bundler_args: --without acceptance
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.4.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.5.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.6.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.7.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.8.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.9.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.10.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 5.0.0"
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 5"
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6"
